### ISSUE TITLE
Question about the width of Bn_Relu_Bits

### ISSUE THREAD

**Issue by Zyq990127** [pulp-platform/dory#13]
Hi!
I noticed that the PenguiNet has two versions in different width of Bn_Relu_Bits, one is 32 and the other is 64.
 
I wonder that what is the difference between them and if there is something to notice when generating an ONNX quantized network  with the Nemo tool if I want the Bn_Relu_Bits to be 32 instead of 64？

when I use DORY to deploy the yolo-v3 tiny backbone(Purely feed forward network) , if the Bn_Relu_Bits is 32 the checksum failed and if the Bn_Relu_Bits is 64 the checksum is OK. Is there something wrong with my quantization process？

Best regards,
Zhu Yuqing

**Comment by FrancescoConti** [comment]
Hi, basically this means that in some instances, the accumulator values post-scaling (i.e., after applying the multiplication factors implied by the BN and by the quantization procedure) do not fit in 32 bits. With Nemo, there is not much control on this beyond trial & error. Using QuantLab as front-end, it is possible to check and fix easier this kind of issue; I will check if there is any open-source code I can share as example.

**Comment by Zyq990127** [comment]
Thank you for your reply.I'd appreciate it if there is any reference code.
