### ISSUE TITLE
Error when using Dory to deploy modified-DroNet.

### ISSUE THREAD

**Issue by ChenMathilda** [pulp-platform/dory#15]
Hi,there
I made the following modifications to Dronet:  add a fully connected layer `self.fc2 = nn.Linear(in_features=fc_size, out_features=3, bias=False)` in Dronet, where ` fc_size = 128*7*7`.
```
x = x.flatten(1)
x_copy = x       
x = self.fc1(x) 
steer = x[:, 0]
coll = self.sig(x[:, 1]) 
x_copy = self.fc2(x_copy)
x_copy = self.relu1(x_copy)
sign = self.softmax(x_copy)    # [a,b,c] #a+b+c = 1

return [steer,coll, sign]
```
which mad the output of dronet like this:
![image](https://user-images.githubusercontent.com/61350967/169233849-7e4e94f8-78b1-4acd-9ec7-dca5162534e3.png)
but I meet following Error: 
```
Traceback (most recent call last):
  File "network_generate.py", line 102, in <module>
    main()
  File "network_generate.py", line 81, in main
    PULP_Nodes_Graph = onnx_m('GAP8', args.chip, args.network_dir + net).parameters_from_onnx(100)
  File "../ONNX_management.py", line 471, in parameters_from_onnx
    new_node = self.create_node(node_element(), first_node, node_iterating, model, PULP_Nodes_Graph)
  File "../ONNX_management.py", line 247, in create_node
    temp = temp.reshape(temp.shape[0], PULP_Nodes_Graph[-1].output_channels, PULP_Nodes_Graph[-1].output_h, PULP_Nodes_Graph[-1].output_w)
ValueError: cannot reshape array of size 18816 into shape (3,2,1,1)
```
I add some print for Debug,and got:
```
Flatten_145
MatMul_146
         MatMul_146
(2, 6272)
2 128 7 7
         1 1
Constant_147
Gather_148
Constant_149
Gather_150
Sigmoid_151
MatMul_152
         MatMul_152
(3, 6272)
3 2 1 1
```
I guess MatMul_152 take the output of MatMul_146(output_w=1,output_h =1) as input which result in this ValueError.
But according to the design of my network, it is planned to use 128\*7\*7 as the input of MatMul_152.
So, How can I solve this Error?
Hoping to hearing from you
Regards,
Mathilda

**Comment by ABurrello** [comment]
The node is not correctly recognized as a branching node. Unfortunately, right now only single output networks with reconverging residual connections are supported. We will support this kind of networks, soon, in a new release.

**Comment by ChenMathilda** [comment]
> The node is not correctly recognized as a branching node. Unfortunately, right now only single output networks with reconverging residual connections are supported. We will support this kind of networks, soon, in a new release.

Hi，
