### ISSUE TITLE
Repository pulp-nn-1d and pulp-nn-mixed not found!

### ISSUE THREAD

**Issue by ESEQU** [pulp-platform/dory#2]
when trying to clone dory with its submodules I get the following error from git:

> Cloning into '/home/quentin/dory/pulp-nn-1d'...
> Username for 'https://github.com': ESEQU
> Password for 'https://ESEQU@github.com':
> remote: Repository not found.
> fatal: repository 'https://github.com/pulp-platform/pulp-nn-1d/' not found
> fatal: clone of 'https://github.com/pulp-platform/pulp-nn-1d' into submodule path '/home/quentin/dory/pulp-nn-1d' failed
> Failed to clone 'pulp-nn-1d'. Retry scheduled

That is because the respective repositories do not exist. I also could not find them anywhere else on github.
Can I still use DORY without them or are they crusial for all functionality?
Also how can I get them?
Thanks in advance

**Comment by ABurrello** [comment]
Hello,
these repositories are only necessary to deploy optimized 1D networks or mixed-precision ones. For standard, supported 8-bits networks you only need the standard pulp-nn repository. You can proceed to the deployment of your neural network also without these 2 repositories.
Best,
Alessio
