### ISSUE TITLE
Dory error during converting nemo's output onnx file 

### ISSUE THREAD

**Issue by mvtkurd** [pulp-platform/dory#27]
hi @ABurrello

with the help of nemo I export the onxx file of my model but I got this error during converting onnx file to C code by dory :

![Screenshot 2022-07-08 180205](https://user-images.githubusercontent.com/32674939/178029832-9b1fe338-645f-46be-949f-127dbe4658e4.jpg)

here is my onnx model :
![my_model onnx (1)](https://user-images.githubusercontent.com/32674939/178033087-5b3fa893-7a7d-48cc-9fe5-1a0fa4c51488.png)

Best,
Milad

**Comment by ABurrello** [comment]
Hello, can you try to use the Alessio-refactoring branch? The error could be given by the first pad node which is not supported. Usually, it is included in the convolutional layers.

**Comment by mvtkurd** [comment]
Dear @ABurrello 

I test it with Alessio-refactoring branch but the same error is occurred! 

![2](https://user-images.githubusercontent.com/32674939/178099895-78cfc0a1-277b-4cf7-9133-7a1092e3783e.jpg)

**Comment by mvtkurd** [comment]
Dear @ABurrello 
I've modified my model but now I have a new error during network generating by dory. Below image shows the error!
![dory_err](https://user-images.githubusercontent.com/32674939/184541946-e65655e4-3382-4dbf-8452-8960b6ec5db2.jpg)
