### ISSUE TITLE
Is Dory supports residual connections networks which has multi-output now?

### ISSUE THREAD

**Issue by ChenMathilda** [pulp-platform/dory#46]
@ABurrello I asked this question [#15 ](https://github.com/pulp-platform/dory/issues/15) before . And you said that Dory will support the multi-output model based on the residual network in the future. Do you have any progress now?

**Comment by ABurrello** [comment]
Unfortunately, we have still not tested the support for this kind of network. Now it is implemented, but not tested. Unfortunately, I do not forsee tests in the near future.

**Comment by ChenMathilda** [comment]
> Unfortunately, we have still not tested the support for this kind of network. Now it is implemented, but not tested. Unfortunately, I do not forsee tests in the near future.

Thanks to your replay,! Please let me know if there are any progress!
