### ISSUE TITLE
Diana_TVM: element-wise sum output transfers are not tiled?

### ISSUE THREAD

**Issue by JosseVanDelm** [pulp-platform/dory#48]
@ABurrello for `Diana_TVM` I noticed while going through both the convolution and the addition template that the output/last DMA call in the tiling loop does not seem to be tiled for the addition (it is tiled for the convolution), and as such it seems to me that it will always write to the same memory address in the output.

I.e. for the final DMA call, there's no `dory_get_tile_3d()` and `l2_y` is set directly in the DMA call field ( `DMA_copy_y.ext = l2_y;` instead of ` DMA_copy_y.ext = l2_y_tile;`).
Is it possible that this will result in an error if the tensor addition gets tiled?

Can you double check this please? Thanks!

**Comment by ABurrello** [comment]
Thanks for the check. It is now updated also for the addition
