### ISSUE TITLE
Failed to run dronet example

### ISSUE THREAD

**Issue by hanyax** [pulp-platform/dory#49]
I used the example here: https://github.com/pulp-platform/dory_examples/tree/60dd66bf1d9ce81c0cdd5f70e51040a332dce8e5/examples/Nemo_examples/8-bits-2D/dronet_complete

and I ran 
`python3 network_generate.py NEMO PULP.PULP_gvsoc./dory/dory_examples/config_files/config_NEMO_dronet.json`

it gives this error:

> Insert tiling parameters per layer inside graph nodes
> RuntimeWarning: Unexpected end-group tag: Not all data was converted
>   return _pywrapcp.Solver_DefaultSolverParameters()
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> F0308 13:22:36.521386     1 constraint_solver.cc:1408] Check failed: parameters.array_split_size() > 0 (0 vs. 0) Were parameters built using Solver::DefaultSolverParameters() ?
> *** Check failure stack trace: ***
> Abort trap: 6

Any idea what might went wrong? Thanks for the help!

**Comment by ABurrello** [comment]
It does not seem an error related to the framework. Is the environment correctly set?
