### ISSUE TITLE
Dory support for Bias add in linear layer?

### ISSUE THREAD

**Issue by hanyax** [pulp-platform/dory#50]
Hi,
I pushed this simple NN through the Nemo quantization process with no problem/ 
<img width="405" alt="Screenshot 2023-03-08 at 4 28 27 PM" src="https://user-images.githubusercontent.com/26683437/223883813-29262764-6f58-4e7e-b374-292f6039b7e2.png">

and the Nemo output this onnx file:
<img width="144" alt="Screenshot 2023-03-08 at 4 30 18 PM" src="https://user-images.githubusercontent.com/26683437/223884058-9f67609d-ad25-436a-8e72-43334d00ac57.png">

However, when I tried to push this through the Dory process, it has an error:
`DORY Frontend Check. Node Add is not accepted inside the DORY Frontend IR.`
caused by the bias add after the matmul layer. I check the code and it is this line: https://github.com/pulp-platform/dory/blob/4f0d2a38848b7c5ba7a70c2a97e6cbc6ba84c4f4/dory/Parsers/DORY_node.py#L124 that prevented the _Add_ layer becomes a "_Addition_" layer.

The other issue #41 mentioned the pattern might not be supported but the linear layer is said to be supported in the README. Could you help me identify the issue here and I am wondering if I could make a small change to make this work.

I am working on a publication for a top-tier journal and will cite these works in my work. Thank you so much for the help!

**Comment by ABurrello** [comment]
Hello,
with NEMO the patter supported for Linears with BN and requantization is Linear + (Mul + add) (BN) + Mul + Shift (Requant). You can check the patterns supported in the NEMO Pattern_Matcher
